version: "3.3"
services:
  express:
    restart: unless-stopped
    build: ./express
    expose:
      - "8080"
    volumes:
      - power-mgmt-db:/etc/power-mgmt
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
volumes:
  power-mgmt-db:
