version: "3.3"
services:
  express:
    restart: unless-stopped
    build: ./express
    expose:
      - "8080"
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
