version: "3.3"
services:
  express:
    restart: unless-stopped
    image: "dashboard/express:${TAG}"
    expose:
      - "8080"
    volumes:
      - power-mgmt-db:/etc/power-mgmt
  nginx:
    restart: unless-stopped
    image: "dashboard/nginx:${TAG}"
    ports:
      - "80:80"
      - "443:443"
volumes:
  power-mgmt-db:
