version: "3.3"
services:
  express:
    restart: unless-stopped
    image: "dashboard/express:${TAG}"
    expose:
      - "8080"
  nginx:
    restart: unless-stopped
    image: "dashboard/nginx:${TAG}"
    ports:
      - "80:80"
      - "443:443"
